### ISSUE TITLE
✷ Zora Network

### ISSUE THREAD

**Issue by z0r0z** [pcaversaccio/xdeployer#157]
### Describe the desired feature:

Add Zora Network, chainId: 7777777

Bridge: https://bridge.zora.energy/

Explorer: https://explorer.zora.energy/

Tip for bridging and deployment :~): https://etherscan.io/tx/0x9ddd2e3bd7b84d8775712e6a437256cf2e6b54f2483686dd7c86493bac754ad7

**Comment by pcaversaccio** [comment]
Shipped https://github.com/pcaversaccio/xdeployer/releases/tag/v2.1.0
