### ISSUE TITLE
[Feature-Request]: Deploy on Manta Pacific Mainnet

### ISSUE THREAD

**Issue by shuhuiluo** [pcaversaccio/xdeployer#183]
### Describe the desired feature:

Could you deploy the contract on [Manta Pacific Mainnet](https://pacific-info.manta.network/)?

The eoa deployer has been [funded](https://pacific-explorer.manta.network/tx/0x1e368229db1e4f355409bafc784b6a7d4d7a8a618ee96d79132e4b2fcdbc7740).

Thank you very much.

**Comment by pcaversaccio** [comment]
hey @shuhuiluo, thanks for funding the deployer address:

- Deployed: https://pacific-explorer.manta.network/address/0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2
- Released: https://github.com/pcaversaccio/xdeployer/releases/tag/v2.1.6
