### ISSUE TITLE
[Feature-Request]: Deploy to Arthera Testnet

### ISSUE THREAD

**Issue by julienbrg** [pcaversaccio/xdeployer#184]
### Describe the desired feature:

May I ask you to deploy the  the `CREATE2` Factory Contract to [Arthera Testnet](https://docs.arthera.net/), please?

Network info: 

- RPC endpoint url: **https://rpc-test.arthera.net**
- Network ID: **10243**

This our [docs](https://docs.arthera.net/build/developing-sc/using-hardhat), [explorer](https://explorer-test.arthera.net/), and [faucet](https://faucet.arthera.net/) (I just sent 10 units to `0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad` as you can see [here](https://explorer-test.arthera.net/tx/0xe5c0b4241e6c3678d26f15a2900b93dd36aae04196b80e05839033c09b7451c0)).

Thank you very much!

**Comment by pcaversaccio** [comment]
Thx I will look into this later. Do you only need the CREATE2 deployment, or is there any specific reason right now to support it via xdeployer as well?

**Comment by julienbrg** [comment]
We'd like to support `xdeployer` as well. It would be great.

**Comment by pcaversaccio** [comment]
- Added to `Create2Deployer` via https://github.com/pcaversaccio/create2deployer/commit/710ba175af337052819dbe2a5c365cd1463dd743
- `Create2Deployer` deployed and verified [`0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2`](https://explorer-test.arthera.net/address/0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2)
- Added to `xdeployer` via https://github.com/pcaversaccio/xdeployer/commit/fc2f4d8b7a0ca2fd114119360596c2fc8e0b00eb
- Test deployment via `xdeployer`: https://explorer-test.arthera.net/tx/0xfe9251eb043b7ef73fa74beadf3a53eaa994a0bf2beb0cb3f6bf0b11f3efa378
- Released via https://github.com/pcaversaccio/xdeployer/releases/tag/v2.1.7 & on `npm` https://www.npmjs.com/package/xdeployer/v/2.1.7
