### ISSUE TITLE
💥 Add Metis Andromeda Network

### ISSUE THREAD

**Issue by carloshc** [pcaversaccio/xdeployer#249]
### Describe the desired feature:

Connection details.
It's a EVM compatible, L2.

https://docs.metis.io/dev/readme/connection-details

**Comment by pcaversaccio** [comment]
@carloshc `xdeployer` is powered by the [`CreateX`](https://github.com/pcaversaccio/createx) contract factory. So I need you to fund my deployer address `0xeD456e05CaAb11d66C4c797dD6c1D6f9A7F352b5` with enough Metis (can you also please send on the Sepolia network so I can deploy it there as well). I'm not familiar with Metis fees, but on a normal EVM network I need around 0.3 ETH to deploy `CreateX`. Let me know once funded and I will deploy and add it to the `xdeployer` plugin.
