### ISSUE TITLE
💥 Add `chainId` to User Configuration

### ISSUE THREAD

**Issue by Confucian-e** [pcaversaccio/xdeployer#284]
### Describe the desired feature:

Now we have to set network name in `networks` field. It takes time to find the correct name that matchs.
Maybe you can consider supporting chainId as an optional feature?

### Code example that solves the feature:

```ts
  xdeploy: {
    contract: "Counter",
    // constructorArgsPath: "", // optional; default value is `undefined`
    salt: "test",
    signer: PrivateKey,
    networks: [1, 10, 56],
    rpcUrls: [Ethereum_RPC_URL, Optimism_RPC_URL, BSC_RPC_URL],
    gasLimit: 1_500_000, // optional; default value is `1.5e6`
  },
  ```

**Comment by pcaversaccio** [comment]
Hey, thanks for opening this feature request. The issue with using `chainId`s is that they aren't inherently clear or human-readable in terms of identifying which network is being used. Additionally, some people prefer to use hex notation for the `chainId`, adding another layer of complexity to parse. I'm hesitant to add `chainId`s because I want to encourage developers to be _explicit_ and deliberate in their choices. Typically, the network name is easier and quicker to identify, while the `chainId` often takes longer to find (and validate) and can sometimes be confused with the `networkId`, which may differ across various chains. Keeping things simple is better in this case.

**Comment by Confucian-e** [comment]
> Hey, thanks for opening this feature request. The issue with using `chainId`s is that they aren't inherently clear or human-readable in terms of identifying which network is being used. Additionally, some people prefer to use hex notation for the `chainId`, adding another layer of complexity to parse. I'm hesitant to add `chainId`s because I want to encourage developers to be _explicit_ and deliberate in their choices. Typically, the network name is easier and quicker to identify, while the `chainId` often takes longer to find (and validate) and can sometimes be confused with the `networkId`, which may differ across various chains. Keeping things simple is better in this case.

I understand your idea. So, could you add a command to the `xdeploy` task that lists all currently available networks? For example, something like `npx hardhat xdeploy --list`.

**Comment by Confucian-e** [comment]
> > Hey, thanks for opening this feature request. The issue with using `chainId`s is that they aren't inherently clear or human-readable in terms of identifying which network is being used. Additionally, some people prefer to use hex notation for the `chainId`, adding another layer of complexity to parse. I'm hesitant to add `chainId`s because I want to encourage developers to be _explicit_ and deliberate in their choices. Typically, the network name is easier and quicker to identify, while the `chainId` often takes longer to find (and validate) and can sometimes be confused with the `networkId`, which may differ across various chains. Keeping things simple is better in this case.
> 
> I understand your idea. So, could you add a command to the `xdeploy` task that lists all currently available networks? For example, something like `npx hardhat xdeploy --list`. Additionally, display their corresponding chainIds so that users can search for the corresponding names based on the chainIds. Of course, this is an optional feature, but I believe it is necessary to include a command that lists all network names.

I made a PR to add a command to list networks. You can check it https://github.com/pcaversaccio/xdeployer/pull/285

**Comment by pcaversaccio** [comment]
Thx for the PR - I enriched it with the chain IDs now:

![image](https://github.com/user-attachments/assets/6b7308a0-b580-4324-aa23-ce84fa851b0c)

Are you ok with this solution?

**Comment by Confucian-e** [comment]
That's awesome. Just merge and publish new npm pacakge.

**Comment by pcaversaccio** [comment]
I will merge it probably tomorrow as I need to revalidate my code first :)

**Comment by pcaversaccio** [comment]
Published the new version: https://github.com/pcaversaccio/xdeployer/releases/tag/v3.1.0.
