### ISSUE TITLE
Add Production Networks

### ISSUE THREAD

**Issue by pcaversaccio** [pcaversaccio/xdeployer#3]
Once the plugin is thoroughly tested on all the test networks, I will add the following production networks:
- [x] `ethmain`
- [x] ` bscmain`
- [x] `optimismmain`
- [x] `arbitrummain`
- [x] `polygon`
- [x] `hecoinfomain`
- [x] `fantommain`
- [x] `avalanche`
- [x] `gnosis`
- [x]  `moonriver`
- [x] `celo`

**Comment by chichke** [comment]
Need it !

**Comment by pcaversaccio** [comment]
In order to deploy I would need around 0.01 ETH/BNB/xdai etc. on the deployer address: 0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad

Anyone (or multiple people) is/are willing to send me some on each of the EVM chains above? Anything left after the deployment will be returned!

**Comment by SimonKraus** [comment]
Funded the account with 10DEV / 0.1MOVR / 1GLMR for Moonbase Alpha / Moonriver / Moonbeam(possible later use)

**Comment by pcaversaccio** [comment]
@chichke most production networks are now included (`gnosis` as well!). If you already want to use it you must download it from my GitHub. I will release the new `npm `version most probably next week once `arbitrummain` & `hecoinfomain` will be also deployed!

**Comment by pcaversaccio** [comment]
Update: `arbitrummain` deployment done. One more to go!

**Comment by pcaversaccio** [comment]
https://github.com/pcaversaccio/xdeployer/releases/tag/v1.1.0
