### ISSUE TITLE
Add Fuse networks

### ISSUE THREAD

**Issue by bertux** [pcaversaccio/xdeployer#7]
To fully use xdeployer for the networks supported by Request Network protocol we will need to add Fuse networks and I can fund the deployer address on these networks after checking CREATE2 is existing there.

**Comment by bertux** [comment]
1 FUSE sent on both networks at the address precised.
For production network it's documented at https://developers.fuse.io/fuse-dev-docs/network-details
For test network it's documented at https://developers.fuse.io/fuse-dev-docs/developer-resources-and-tools#testnets and the ChainID is 123
Be careful to set the gas price to 1 GWei at least for the testnet because it may still have 0 GWei as default grice.
Let me know if I can help.

**Comment by pcaversaccio** [comment]
Ok thx for that: I just published the new release [`v.1.1.5`](https://github.com/pcaversaccio/xdeployer/releases/tag/v1.1.5) & pushed it to `npm`. I also already tried it [here](https://explorer.fuse.io/tx/0x6838fa1d7e096e189c43d9c91f55137a1b807216c0b248d189f676a5755c0796/token-transfers) successfully. While I successfully verified the contract on the production not, my verification is pending for 30mins on the spark block explorer. Can you help me with this?

**Comment by bertux** [comment]
Sorry for the delay and thank you for your fast deployment and feedback.
>
> Ok thx for that: I just published the new release [`v.1.1.5`](https://github.com/pcaversaccio/xdeployer/releases/tag/v1.1.5) & pushed it to `npm`. I also already tried it [here](https://explorer.fuse.io/tx/0x6838fa1d7e096e189c43d9c91f55137a1b807216c0b248d189f676a5755c0796/token-transfers) successfully. While I successfully verified the contract on the production not, my verification is pending for 30mins on the spark block explorer. Can you help me with this?
> 
> Also, you should fix this problem with the 0 gwei issue in the RPC providers since my plugin relies on the injected providers directly and if the RPC providers just provide a default price that is not accepted by the network the transaction broadcasted by the `xdeployer` will obviously not succeed (I use ethers.js under the hood FYI).

I've already made the same feedback to Fuse tech team about the current bugs in the Spark so there is nothing more I can help with these current bugs.
