### ISSUE TITLE
[Feature-Request]: Add Canto EVM

### ISSUE THREAD

**Issue by z0r0z** [pcaversaccio/xdeployer#99]
### Describe the desired feature:

Chain ID: 7700

https://docs.canto.io/user-guides/connecting-to-canto

**Comment by pcaversaccio** [comment]
@z0r0z thanks for opening the request: could you please fund my deployer address `0x554282Cf65b42fc8fddc6041eb24ce5E8A0632Ad` with some CANTO for the `CREATE2` deployer deployment?

**Comment by pcaversaccio** [comment]
Edit: no more funding needed as I got funding from @FukkenClown69 on Discord.

**Comment by z0r0z** [comment]
amazing!

**Comment by pcaversaccio** [comment]
Released via [`v1.1.26`](https://github.com/pcaversaccio/xdeployer/releases/tag/v1.1.26).
